### ISSUE TITLE
Feature request: Drag and drop to add the same node to another stream.

### ISSUE THREAD

**Issue by grooveboxunited** [saqimtiaz/streams#10]
Right now I am aware of two ways to copy nodes to a different Stream with drag and drop: 

* Holding shift creates a new node with the text transcluded.
* Holding control creates a new node with the exact same text.

I have found instances where it is useful to have the exact same node appear in separate streams, so that if I edit one of them the other is also updated. This is different to just a transclusion since it is bi-directional.

Currently I do this by just adding the name of the tiddler to the stream-list of the new stream, but it would be cool if it could be done with a drag and drop mechanism. Maybe holding the alt key or ctrl+shift or something.

Anyway thanks so much for the great plugin!

**Comment by saqimtiaz** [comment]
> Currently I do this by just adding the name of the tiddler to the stream-list of the new stream, but it would be cool if it could be done with a drag and drop mechanism. Maybe holding the alt key or ctrl+shift or something.

This will eventually cause problems for you, as Streams relies on the parent field of a node which can only point to a single tiddler. As such, accommodating the same node in multiple streams would require an extensive overhaul of how Streams maintains relationships. Furthermore, the parent field mitigates certain performance issues to some extent, and moving away from this pattern would only exacerbate the problem. See #8 

As such, this feature will not be implemented.
