### ISSUE TITLE
Questions about access control ?

### ISSUE THREAD

**Issue by huruka** [saqimtiaz/streams#12]
Refer to this [page](https://tiddlywiki.com/static/WebServer%2520Authorization.html), I started tw with the following command on my computer:

`tiddlywiki mywiki --listen host=127.0.0.1 credentials="./users.csv" "readers=(anon)" writers=mary`

It can be found that visitors cannot edit the Wiki, but there are exceptions:

streams plugin can still works? click the + button, double-click the node, etc...

Is there anything else I need to set? 

edit: oh, I see, although it can be modified, it seems that it has not been saved

**Comment by huruka** [comment]
Nevertheless, it is best if can completely prohibit editing through streams. 
Sometimes forget to log in when enter the notes, and then record some content and find that it is not saved. It will be very frustrating...

**Comment by saqimtiaz** [comment]
It's a fair request. I've never used TW with any kind of authentication so I'll have to look into the mechanism for determining if the wiki should be read only.

**Comment by saqimtiaz** [comment]
Fixed in https://github.com/saqimtiaz/streams/commit/4874bf3f42d81d944073bf02e88abb21b4d3cfa3

Let me know if this is still an issue in Stream 0.2.17

**Comment by huruka** [comment]
good, i will have a try
