### ISSUE TITLE
Support for streams in tiddlyclip 

### ISSUE THREAD

**Issue by arunnbabu81** [saqimtiaz/streams#27]
https://github.com/buggyj/tiddlyclip-plugin/issues/35

As mentioned in the issue linked above, is it possible to add support for streams in tiddlyclip. Is there anything you can do from your part regarding this. If not, feel free to close this issue.

**Comment by saqimtiaz** [comment]
I've had a quick look and it seems that the work involved is entirely tiddlyclip specific and not even in normal wiki syntax. As such unfortunately I don't think there is anything I can do to be of assistance. 

Adding a node to an existing tiddler involves adding a parent field in the new node pointing to the parent tiddler, and adding the new node to the stream-list field of the parent. You may want to consider running actions in tiddlywiki after clipping to move the tiddler created by tiddlyclip into a Streams structure.

**Comment by arunnbabu81** [comment]
Can anything be done using text slicer plug in or the excise text editor toolbar button so that the excised text becomes the child nodes of parent tiddler

**Comment by arunnbabu81** [comment]
Refer to [this discussion](https://github.com/buggyj/tiddlyclip-plugin/issues/35#issuecomment-1030414535) in case anyone is interested
