### ISSUE TITLE
swiping for context menu not working on 5.2.0 pre-release in ios 14.8 safari

### ISSUE THREAD

**Issue by makiaea** [saqimtiaz/streams#35]
hi saq, really loving streams, thanks! just did a few days of testing with the tw prerelease and noticed this issue with the swiping, confirmed with a fresh 5.2.0 empty and latest streams 1.2.22, on ios 14.8 ipad safari. also tested with ios 14.3 on iphone safari. hth!

**Comment by saqimtiaz** [comment]
There is a core change in the `<$eventcatcher>` widget that might be responsible, for which I have submitted a PR: https://github.com/Jermolene/TiddlyWiki5/pull/6048
Let's see if that fixes it, unfortunately I cannot test on iOS directly.

**Comment by saqimtiaz** [comment]
@makiaea you can test here to see if the problem has been resolved on iOS:
https://saqimtiaz.github.io/streams/prerelease/beta.html

**Comment by makiaea** [comment]
works really well, thanks so much!
![IMG_0014](https://user-images.githubusercontent.com/228018/133907502-ea017cda-28a3-460c-9246-673903cd9d4d.png)
