### ISSUE TITLE
Duplicate node bug

### ISSUE THREAD

**Issue by kriddly** [saqimtiaz/streams#36]
Hello!
Huge thank you for the plugin, it has quickly become an integral part of my note-taking workflow.

I finally elucidated a minor bug that kept slightly annoying me every now and then, that ends up mispositioning a node in two places. Tested in https://saqimtiaz.github.io/streams/.

Imagine a following node structure:

- (1)Parent node(2)to be split
- - (3)Child node

Now I split the parent node in half by pressing enter at the middle.
Child node is now only in the stream list of "(2)to be split" but the parent of "(3)Child node" is still "(1)Parent node"

- (1)Parent node
- (2)to be split
- - (3)Child node

Thus, trying to unindent the (3)Child node results in:

- (1)Parent node
- (3)Child node
- (2)to be split
- - (3)Child node

Thought I'd let you know in case this hasn't come up yet.
Best wishes
K

**Comment by saqimtiaz** [comment]
This should be resolved, please test in Streams 1.2.23 and confirm.

**Comment by kriddly** [comment]
Issue fixed

**Comment by saqimtiaz** [comment]
Thank you for reporting the bug and for providing steps to recreate it.
