### ISSUE TITLE
bug: when the fold-bar is switched on, the breadcrumbs are obscured

### ISSUE THREAD

**Issue by oflg** [saqimtiaz/streams#39]
![image](https://user-images.githubusercontent.com/42492105/139624440-6a4aeb27-4d09-425e-8be0-091a8cf6bae6.png)

![image](https://user-images.githubusercontent.com/42492105/139624490-569aa26d-1fba-4d48-9305-24bd6fd91565.png)

**Comment by saqimtiaz** [comment]
My first instinct is that the breadcrumbs should be hidden when the tiddler is folded. Is that what you are expecting?

**Comment by oflg** [comment]
I have no preference for it to be shown or not shown, as long as it is not obscured.

**Comment by saqimtiaz** [comment]
Fixed in https://github.com/saqimtiaz/streams/commit/814bc9e604a55ec91d9d7b2600905469a2cfa10b
