### ISSUE TITLE
How to return current node title

### ISSUE THREAD

**Issue by kebifurai** [saqimtiaz/streams#4]
I want to return the current node title in the same way `<stream-root-title>` returns the title of the current tiddler, how can I do it?

**Comment by saqimtiaz** [comment]
@kebifurai inside a node, <<currentTiddler>> points to the node and not the story tiddler.

You can also access the immediate parent via {{!!parent}} and the storyTiddler (root node) via <<stream-root-title>>

**Comment by kebifurai** [comment]
sorry, I didn't use the code block in the question.

**Comment by saqimtiaz** [comment]
@kebifurai apologies, I've corrected the above comment.
Inside a node, `<<currentTiddler>>` will give you the node title.

**Comment by kebifurai** [comment]
Thank you for the fast reply!

**Comment by kebifurai** [comment]
Sorry to reopen but how do I recall the title of a node outside that node?
`<<currentTiddler>>` returns the title of the note where my macro is defined not the actual node, but `<<stream-root-title>>` works just fine, what am I missing...

**Comment by saqimtiaz** [comment]
> Sorry to reopen but how do I recall the title of a node outside that node?

I don't understand what this means or what you are attempting to do.

> `<<currentTiddler>>` returns the title of the note where my macro is defined not the actual node, but `<<stream-root-title>>` works just fine, what am I missing...

This seems related to your code and how it is being used within Streams, most likely you are re-assigning currentTiddler to a different value in your macro. I cannot offer further assistance without seeing your code.

**Comment by kebifurai** [comment]
I'm using Stream in combination with another plugin [TiddlyRemember](https://sobjornstad.github.io/TiddlyRemember/)

TiddlyRemember also uses an ID field generated from the current time, the same way Stream does.
TiddlyRemember has the following macro:

```
$:/plugins/sobjornstad/TiddlyRemember/toolbar/remembercz

\define getMacro()
<<remembercz "$(clozeid)$"
	"Cloze">>
\end

<$set name=clozeid
      value=<<now "[UTC]YYYY0MM0DD0hh0mm0ss0XXX">> >
	<$action-sendmessage
		$message="tm-edit-text-operation"
		$param="replace-selection"
		text=<<getMacro>>
	/>
</$set>
```

I want to change the clozeid value to the already generated id of the node I'm editing.
I tried to use`<<currentTiddler>>` instead of `<<now "[UTC]YYYY0MM0DD0hh0mm0ss0XXX">>` but when I recall this toolbar with a shortcut, it returns `$:/plugins/sobjornstad/TiddlyRemember/toolbar/remembercz` instead of the node title.

**Comment by saqimtiaz** [comment]
This isn't an issue related to Streams, but rather to TiddlyRemember. 

Trying to make TiddlyRemember use the `currentTiddler` variable in  a regular tiddler (not a Streams node) causes the same issue. Try using the `targetTiddler` variable set by the code that setups the edit toolbar.

If that doesn't help, I suggest posting on the [google group](https://groups.google.com/forum/#!forum/tiddlywiki) and asking for assistance.
