### ISSUE TITLE
Messy "recent" tab

### ISSUE THREAD

**Issue by linonetwo** [saqimtiaz/streams#40]
![图片](https://user-images.githubusercontent.com/3746270/152734105-6d8d13bb-4860-49db-9787-8f9a4c4b6f1d.png)

How to fix this?

**Comment by saqimtiaz** [comment]
@linonetwo one approach is to only show the root tiddler for each node in the timeline, as documented in the FAQ:
https://saqimtiaz.github.io/streams/#FAQs%2FHow%20can%20I%20show%20only%20the%20stream%20root%20tiddlers%20in%20the%20timeline%3F

**Comment by linonetwo** [comment]
Thanks, I will tell that user in our QQ group.
