### ISSUE TITLE
Renaming a Tiddler doesn't rename its nodes

### ISSUE THREAD

**Issue by kebifurai** [saqimtiaz/streams#7]
Relink says it is going to rename the nodes but it doesn't, is this a bug?

![image](https://user-images.githubusercontent.com/49175327/90459993-e2a5e900-e13d-11ea-94a7-63bd5cd8f030.png)

**Comment by saqimtiaz** [comment]
"Use Relink to **_update_** New Note to New Note 1 across all other tiddlers"

Note: **_update_**, not rename. This is standard TW behaviour (extended by Relink) when renaming a tiddler, you get the option to update references to it. 

If you want to rename all sub-nodes of a tiddler you will need to handle that yourself.
