### ISSUE TITLE
Is it possible to have both non-outline part and outline in a single tiddler?

### ISSUE THREAD

**Issue by linonetwo** [saqimtiaz/streams#9]
In Notion, we can have an outline and a normal note inside the same page. Can we do this in tiddlywiki with streams?

**Comment by saqimtiaz** [comment]
@linonetwo I have no familiarity with Notion, so please explain in more general terms what your question is.

**Comment by linonetwo** [comment]
<img width="312" alt="Screen Shot 2020-10-24 at 11 27 31 PM" src="https://user-images.githubusercontent.com/3746270/97085519-80db9100-1650-11eb-8e65-0d934c16cdfe.png">

Like this, mixed normal wikitext and list

**Comment by saqimtiaz** [comment]
@linonetwo thank you for the example. Currently this is not supported. The plan for 2.0 is to support different types of node types. So a node could be formatted as a list item or something else. But that's still a fair way down the road as I'm being kept rather busy with other commitments.

Do note however that each node in Streams can contain any content, even multiline. So while it might not look visually the same as your example you might be able to achieve the same goals.

**Comment by saqimtiaz** [comment]
Also note that a tiddler can have it's own content in its text field, which is displayed before any nodes that it might have.

**Comment by linonetwo** [comment]
I think before install streams, tiddler is the first class note type, but after install streams, the first class note type is the streams outline note.

Maybe what I want is actually

1. when type - , automatically insert a {{transclusion to a new tiddler}}
2. can directly edit that tiddler

But that will be far complicated.

Thanks for your explanation.

**Comment by saqimtiaz** [comment]
@linonetwo note that you can still open the individual stream nodes directly for editing, by clicking the bullet symbol.
